#!/usr/bin/env bash
# displays a list of currently running processes
# Must show all processes, for all users including whose might not have a TTY
# Displays in a user-oriented format
# Show process hierarchy
ps -faux
