#!/usr/bin/env bash
# display:
#+ the content of the current directory in a list format
#+ where only the part of the name after the first dash is displayed

LS="$(ls)"
for i in $LS; do
    echo "$i" | cut -d - -f2
done
