#!/usr/bin/env bash
# gives information about the school file:
#+ check if the file exist and print output msg

fichier="school"
if [ -e $fichier ]; then
    echo "school file exists"
    if [ -s $fichier ]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi

    if [ -f $fichier ]; then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
